<a href="https://colab.research.google.com/github/Jingkang05/WIA1007/blob/main/tutorial3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import numpy as np
# 1. Create a numpy array of size 2 x 2
arr_2x2 = np.array([[1, 2],[3, 4]])

print("--- 2x2 Array ---")
print(arr_2x2)
print("Shape:", arr_2x2.shape)


--- 2x2 Array ---
[[1 2]
 [3 4]]
Shape: (2, 2)


In [21]:
# 2. Create a random numpy array of size 3 x 4
arr_rand_3x4 = np.random.rand(3, 4)

print(" 3x4 Random Array ")
print(arr_rand_3x4)
print("Shape:", arr_rand_3x4.shape)


 3x4 Random Array 
[[0.0466879  0.09017976 0.11087772 0.62471955]
 [0.79342122 0.67448288 0.82652492 0.71476824]
 [0.03096875 0.2115216  0.72593247 0.98576395]]
Shape: (3, 4)


In [22]:
# 3. Create a numpy array of ones and a numpy array of zeroes
arr_ones = np.ones((3, 3))
arr_zeros = np.zeros((3, 3))

print(" 3x3 Array of Ones ")
print(arr_ones)

print(" 3x3 Array of Zeros ")
print(arr_zeros)


 3x3 Array of Ones 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
 3x3 Array of Zeros 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [23]:
# 4. Create a random numpy array of size 6x3 and transpose it
arr_6x3 = np.random.rand(6, 3)
arr_transposed = arr_6x3.T

print("\n--- Transposed 3x6 Array ---")
print(arr_transposed)
print("Transposed Shape:", arr_transposed.shape)



--- Transposed 3x6 Array ---
[[0.93544695 0.55721845 0.47539356 0.56343881 0.96138564 0.9109178 ]
 [0.70719748 0.09508444 0.00783554 0.64603726 0.64751735 0.18444539]
 [0.59111836 0.68141525 0.48518891 0.64595917 0.74460665 0.21356903]]
Transposed Shape: (3, 6)


In [24]:
# 5. Create two random numpy array of size n x p and p x m and then compute the dot product

# Let's define our dimensions:
n = 4
p = 2
m = 5

# Create the two random arrays
arr_nxp = np.random.rand(n, p)  # Shape (4, 2)
arr_pxm = np.random.rand(p, m)  # Shape (2, 5)

# Compute the dot product using np.dot()
dot_product = np.dot(arr_nxp, arr_pxm)

print("\n--- Dot Product ---")
print("Shape of first array:", arr_nxp.shape)
print("Shape of second array:", arr_pxm.shape)
print("\nResulting Dot Product:")
print(dot_product)
print("Result Shape:", dot_product.shape)


--- Dot Product ---
Shape of first array: (4, 2)
Shape of second array: (2, 5)

Resulting Dot Product:
[[0.96835771 0.27721031 0.29848379 0.62912173 0.3115502 ]
 [0.95808046 0.35258441 0.33290529 0.59782192 0.32230691]
 [0.41390278 0.04178452 0.09076522 0.29301963 0.11939164]
 [0.89762288 0.33109914 0.31226463 0.55985752 0.30210559]]
Result Shape: (4, 5)
